/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan10;

import static pertemuan10.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lendriana
 * TGL: 24 MEI 2025
 */
public class fMahasiswa extends javax.swing.JFrame {
    DefaultTableModel DTM = new DefaultTableModel();

    /**
     * Creates new form fMahasiswa
     */
    public fMahasiswa() throws SQLException {
        initComponents();
        
        tblMhs.setModel(DTM);
        DTM.addColumn("NIM");
        DTM.addColumn("Nama Mahasiswa");
        DTM.addColumn("Jurusan");
        DTM.addColumn("Alamat");
        
        String[] opsiJUR = {"Pilih Jurusan", "KAB", "MTI", "DKV", "TIPAR", "RSK", "B"};
        cbJUR.removeAllItems();
        for( int i=0;i<7;i++){
        cbJUR.addItem(opsiJUR[i]);
        }
        lsdtmhs();
        clearform();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txNIM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNAMA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txJUR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txALAMAT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMhs = new javax.swing.JTable();
        cBaru = new javax.swing.JButton();
        cUbah = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();
        cTutup = new javax.swing.JButton();
        cbJUR = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 350));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Data Mahasiswa");

        jLabel2.setText("NIM");

        jLabel3.setText("Nama Mahasiswa");

        txNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNAMAActionPerformed(evt);
            }
        });

        jLabel4.setText("Jurusan");

        txJUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJURActionPerformed(evt);
            }
        });

        jLabel5.setText("Alamat");

        txALAMAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txALAMATActionPerformed(evt);
            }
        });

        tblMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMhs);

        cBaru.setText("Baru");
        cBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBaruActionPerformed(evt);
            }
        });

        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        cHapus.setText("Hapus");

        cTutup.setText("Tutup");

        cbJUR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txNAMA, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(txNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(txJUR, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(txALAMAT, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cTutup))
                    .addComponent(jLabel3)
                    .addComponent(cbJUR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txJUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(cbJUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBaru)
                            .addComponent(cUbah)
                            .addComponent(cHapus)
                            .addComponent(cTutup)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txJURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJURActionPerformed

    }//GEN-LAST:event_txJURActionPerformed

    private void txALAMATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txALAMATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txALAMATActionPerformed

    private void txNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNAMAActionPerformed

    private void cBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBaruActionPerformed
       
        if(cBaru.getText().equals("Baru")){
             clearform();
             cBaru.setText("Simpan");
             cTutup.setText("Batal");
             cUbah.setEnabled(false);
             cHapus.setEnabled(false);
        }else{
            try {
                storeData();
                lsdtmhs();
            } catch (SQLException ex) {
                Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
            }
            cBaru.setText("Baru");
            cTutup.setText("Tutup");
            cUbah.setEnabled(true);
            cHapus.setEnabled(true);
        }       
    }//GEN-LAST:event_cBaruActionPerformed

    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
        if(cUbah.getText().equals("Ubah")){
             clearform();
             cUbah.setText("Simpan");
        }else{
            cUbah.setText("Ubah");
        }  
    }//GEN-LAST:event_cUbahActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
      
    }//GEN-LAST:event_formMouseClicked

    private void tblMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMhsMouseClicked
       txNIM.setText(tblMhs.getValueAt(tblMhs.getSelectedRow(), 0).toString() );
        txNAMA.setText(tblMhs.getValueAt(tblMhs.getSelectedRow(), 1).toString() );
        txJUR.setText(tblMhs.getValueAt(tblMhs.getSelectedRow(), 2).toString() );
        txALAMAT.setText(tblMhs.getValueAt(tblMhs.getSelectedRow(), 3).toString() );
    }//GEN-LAST:event_tblMhsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fMahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBaru;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cTutup;
    private javax.swing.JButton cUbah;
    private javax.swing.JComboBox<String> cbJUR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMhs;
    private javax.swing.JTextField txALAMAT;
    private javax.swing.JTextField txJUR;
    private javax.swing.JTextField txNAMA;
    private javax.swing.JTextField txNIM;
    // End of variables declaration//GEN-END:variables

    private void lsdtmhs() throws SQLException{
        Connection cnn = koneksi();
        
        DTM.getDataVector().removeAllElements();
        DTM.fireTableDataChanged();
        
        if( !cnn.isClosed()){
            PreparedStatement PS = cnn.prepareStatement("SELECT * FROM mhs;");
            ResultSet RS = PS.executeQuery();
            while( RS.next() ){
                Object[] datamhs = new Object[4];
                    datamhs[0] = RS.getString("NIM");
                    datamhs[1] = RS.getString("NAMA");
                    datamhs[2] = RS.getString("JURUSAN");
                    datamhs[3] = RS.getString("ALAMAT");
                    
                    DTM.addRow(datamhs);
            }
        }
    }
    
    private void clearform(){
    txNAMA.setText("");
    txNIM.setText("");
    txJUR.setText("");
    txALAMAT.setText("");
    }

    private void storeData() throws SQLException {
       Connection cnn = koneksi();
       String nim = txNIM.getText();
       String nama = txNAMA.getText();
       String jur = txJUR.getText();
       String alamat = txALAMAT.getText();
       
       if(!cnn.isClosed()){
           PreparedStatement PS = cnn.prepareStatement("INSERT INTO mhs(NIM, NAMA, JURUSAN, ALAMAT) VALUES(?,?,?,?);");
           PS.setString(1, nim);
           PS.setString(2, nama);
           PS.setString(3, jur);
           PS.setString(4, alamat);
           PS.executeUpdate();
           cnn.close();
       }
       
    }
}
